---
title: Oarfish
github_username: p-jo
repository: p-jo/oarfish
baseurl: /oarfish
url: https://p-jo.github.io
author: Petter Joelson
twitter:
  username: p_jo
logo: "/assets/images/King_of_herrings.png"
plugins:
- jekyll-seo-tag
exclude:
- ".sass-cache"
- node_modules
- Gemfile*
- Gruntfile.js
- package*.json
